name: Build Despair Browser

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout brave-browser
        uses: actions/checkout@v4
        with:
          repository: 'brave/brave-browser'
          path: 'brave-browser'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout brave-core
        uses: actions/checkout@v4
        with:
          repository: 'brave/brave-core'
          path: 'brave-browser/src/brave'

      - name: Initialize Shallow Build Environment
        run: |
          set -ex # Exit on error, print commands
          cd brave-browser/src/brave 
          npm install

          npm run init -- --init --no-history -D --target_os=android --target_arch=arm64

      - name: Debloat - Disable Brave Rewards
        run: |
          cd brave-browser/src/brave
          # Backup file .env untuk keamanan
          cp .env .env.backup
          # Hapus nilai dari endpoint Rewards
          sed -i 's/rewards_grant_dev_endpoint=.*/rewards_grant_dev_endpoint=/' .env
          sed -i 's/rewards_grant_prod_endpoint=.*/rewards_grant_prod_endpoint=/' .env
          sed -i 's/rewards_grant_staging_endpoint=.*/rewards_grant_staging_endpoint=/' .env
          echo "Brave Rewards endpoints disabled."

      - name: Debloat - Disable Brave Wallet
        run: |
          # Lokasi komponen UI bisa bervariasi, kita cari yang umum
          WALLET_PATH="brave-browser/src/brave/browser/ui/views/wallet"
          if [ -d "$WALLET_PATH" ]; then
            echo "Brave Wallet component found, disabling..."
            mv "$WALLET_PATH" "${WALLET_PATH}_disabled"
          else
            echo "Brave Wallet component not found, skipping."
          fi

      - name: Debloat - Disable Brave VPN
        run: |
          # Lokasi komponen UI bisa bervariasi, kita cari yang umum
          VPN_PATH="brave-browser/src/brave/browser/ui/views/vpn"
          if [ -d "$VPN_PATH" ]; then
            echo "Brave VPN component found, disabling..."
            mv "$VPN_PATH" "${VPN_PATH}_disabled"
          else
            echo "Brave VPN component not found, skipping."
          fi

      - name: Debloat - Disable Brave Leo (AI)
        run: |
          AI_CHAT_BUILDFLAGS="brave-browser/src/brave/components/ai_chat/core/common/buildflags/buildflags.gni"
          if [ -f "$AI_CHAT_BUILDFLAGS" ]; then
            echo "Disabling Brave Leo (AI Chat)..."
            # Ganti 'enable_ai_chat = true' menjadi 'enable_ai_chat = false'
            sed -i 's/enable_ai_chat = true/enable_ai_chat = false/' "$AI_CHAT_BUILDFLAGS"
          else
            echo "AI Chat buildflags not found, skipping."
          fi

      - name: Debloat - Disable Brave Sync
        run: |
          PREFS_FILE="brave-browser/src/brave/browser/default_prefs/master_preferences.json"
          echo "Disabling Brave Sync by default..."
          # Buat file master_preferences.json untuk menonaktifkan Sync
          echo '{"sync":{"managed":"false"}}' > "$PREFS_FILE"

      - name: Build Brave Browser
        run: |
          cd brave-browser
          npm run build Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: brave-browser-build
          path: brave-browser/out/Release/ # Lokasi output build Brave
      # - name: Apply Debloating Patches
      #   ...
      # - name: Build Browser
      #   run: npm run build
      # - name: Upload Artifact
      #   ...
